apiVersion: apps/v1
kind: Deployment
metadata:
  name: stepex-e-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stepex-e-com
  template:
    metadata:
      labels:
        app: stepex-e-com
    spec:
      containers:
      - name: stepex-e-com
        image: rafikp10/stepex-e-com:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://rafikpmty:hPVIsrVXBihPdKWd@cluster0.i3fnlhj.mongodb.net/stepex"
        - name: PORT
          value: "3000"
        - name: APP_EMAIL_ID
          value: "rafikpmty@gmail.com"
        - name: APP_PASSWORD
          value: "gxbwbnicdhrdkcsi"
        - name: RAZORPAY_ID_KEY
          value: "rzp_test_b0szQvJZ7F009R"
        - name: RAZORPAY_SECRET_KEY
          value: "D1VdaqMPK600mUoJe9HbkgUl"
