apiVersion: v1
kind: Service
metadata:
  name: stepex-e-com
spec:
  type: NodePort
  selector:
    app: stepex-e-com
  ports:
    - protocol: TCP
      port: 3000       # The external service port
      targetPort: 3000 # The container port
